# Warning
- color: "ee0701"
  description: "Categorize bug reports."
  name: ":warning: bug"
- color: "ee0701"
  description: "Categorize vulnerability reports."
  name: ":warning: vulnerability"

# Highlight
- color: "0e8a16"
  description: "Good for newcomers."
  name: ":fire: good first issue"
- color: "0e8a16"
  description: "Extra attention is needed."
  name: ":fire: help wanted"

# Cancel
- color: "b60205"
  description: "This issue or pull request already exists."
  name: ":pray: duplicate"
- color: "b60205"
  description: "This will not be worked on."
  name: ":pray: wontfix"

# Size
- color: "cfd3d7"
  description: "Extra Small size issue or PR."
  name: "size/XS"
- color: "cfd3d7"
  description: "Small size issue or PR."
  name: "size/S"
- color: "cfd3d7"
  description: "Medium size issue or PR."
  name: "size/M"
- color: "cfd3d7"
  description: "Large size issue or PR."
  name: "size/L"
- color: "cfd3d7"
  description: "Extra Large size issue or PR."
  name: "size/XL"

# Modules
- color: "fbca04"
  description: "This issue or pull request is related to alb module."
  name: ":floppy_disk: alb"
- color: "fbca04"
  description: "This issue or pull request is related to nlb module."
  name: ":floppy_disk: nlb"
- color: "fbca04"
  description: "This issue or pull request is related to gwlb module."
  name: ":floppy_disk: gwlb"
- color: "fbca04"
  description: "This issue or pull request is related to alb-listener module."
  name: ":floppy_disk: alb-listener"
- color: "fbca04"
  description: "This issue or pull request is related to nlb-listener module."
  name: ":floppy_disk: nlb-listener"
- color: "fbca04"
  description: "This issue or pull request is related to alb-instance-target-group module."
  name: ":floppy_disk: alb-instance-target-group"
- color: "fbca04"
  description: "This issue or pull request is related to alb-ip-target-group module."
  name: ":floppy_disk: alb-ip-target-group"
- color: "fbca04"
  description: "This issue or pull request is related to alb-lambda-target-group module."
  name: ":floppy_disk: alb-lambda-target-group"
- color: "fbca04"
  description: "This issue or pull request is related to nlb-instance-target-group module."
  name: ":floppy_disk: nlb-instance-target-group"
- color: "fbca04"
  description: "This issue or pull request is related to nlb-ip-target-group module."
  name: ":floppy_disk: nlb-ip-target-group"
- color: "fbca04"
  description: "This issue or pull request is related to nlb-alb-target-group module."
  name: ":floppy_disk: nlb-alb-target-group"
- color: "fbca04"
  description: "This issue or pull request is related to gwlb-instance-target-group module."
  name: ":floppy_disk: gwlb-instance-target-group"
- color: "fbca04"
  description: "This issue or pull request is related to gwlb-ip-target-group module."
  name: ":floppy_disk: gwlb-ip-target-group"
