# Modules
":floppy_disk: alb":
- modules/alb/**/*
":floppy_disk: nlb":
- modules/nlb/**/*
":floppy_disk: gwlb":
- modules/gwlb/**/*
":floppy_disk: alb-listener":
- modules/alb-listener/**/*
":floppy_disk: nlb-listener":
- modules/nlb-listener/**/*
":floppy_disk: alb-target-group":
- modules/alb-target-group/**/*
":floppy_disk: instance-target-group":
- modules/instance-target-group/**/*
":floppy_disk: ip-target-group":
- modules/ip-target-group/**/*
":floppy_disk: lambda-target-group":
- modules/lambda-target-group/**/*
