# Modules
":floppy_disk: alb":
- modules/alb/**/*
":floppy_disk: nlb":
- modules/nlb/**/*
":floppy_disk: gwlb":
- modules/gwlb/**/*
":floppy_disk: alb-listener":
- modules/alb-listener/**/*
":floppy_disk: nlb-listener":
- modules/nlb-listener/**/*
":floppy_disk: alb-instance-target-group":
- modules/alb-instance-target-group/**/*
":floppy_disk: alb-ip-target-group":
- modules/alb-ip-target-group/**/*
":floppy_disk: alb-lambda-target-group":
- modules/alb-lambda-target-group/**/*
":floppy_disk: nlb-instance-target-group":
- modules/nlb-instance-target-group/**/*
":floppy_disk: nlb-ip-target-group":
- modules/nlb-ip-target-group/**/*
":floppy_disk: nlb-alb-target-group":
- modules/nlb-alb-target-group/**/*
":floppy_disk: gwlb-instance-target-group":
- modules/gwlb-instance-target-group/**/*
":floppy_disk: gwlb-ip-target-group":
- modules/gwlb-ip-target-group/**/*
